name: 'V1-B$(Date:yyyyMMdd)-$(BuildID)'

parameters:
  - name: forceDevDeploy
    displayName: "Deploy to DEV?"
    type: boolean
    default: false
  - name: deployToSecondary
    displayName: "Select Secondary Region"
    type: string
    default: PRD
    values:
      - None
      - DEV
      - TST
      - PRE
      - PRD

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
     - src/Defra.PTS.Dynamics.Functions/*
     - test/*

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-TRD/Defra.TRD.Pipeline.Common
      type: git
      ref: master

variables:
  APIName: nipts-pts-dynamics-functions

extends:
  template: /templates/basic-webapp-deploy-pipeline.yaml@PipelineCommon
  parameters:
    forceDevDeploy: ${{ parameters.forceDevDeploy }}
    deployToSecondary: ${{ parameters.deployToSecondary}}
    appName: $(APIName)
    appProject: PTS
    sqlProject: TRS
    appType: 'functionApp'
    appInstanceNumber: $(nc-region-id)07
    scr: GH
    buildProjects: |
      **/*Functions.csproj
      **/*Tests.csproj
    publishProject: '**/*Functions.csproj'
    setupMiUser: 'true'
    connectionStrings: '[{"name": "sql_db", "value": "Server=tcp:$(sqlServerName),1433;Database=pet-travel;Authentication=Active Directory Managed Identity;", "type": "SQLAzure", "slotSetting": false}]'
    appSettingsEnv:
        dev: >-
          -DynamicOptions:Authority "https://login.microsoftonline.com/"
          -DynamicOptions:ApiVersion "9.1"
          -AzureServiceBusOptions:SubmitQueueName "defra.trade.pts.application.submit"
          -AzureServiceBusOptions:UpdateQueueName "defra.trade.pts.application.update"
          -KeyVaultUri "https://$(Environment.Name)TRD$(nc-function-infrastructure)$(nc-resource-keyvault)1001.vault.azure.net/"
          -ServiceBusConnection:fullyQualifiedNamespace "$(environment)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001.servicebus.windows.net"
        tst: >-
          -DynamicOptions:Authority "https://login.microsoftonline.com/"
          -DynamicOptions:ApiVersion "9.1"
          -AzureServiceBusOptions:SubmitQueueName "defra.trade.pts.application.submit"
          -AzureServiceBusOptions:UpdateQueueName "defra.trade.pts.application.update"
          -KeyVaultUri "https://$(Environment.Name)TRD$(nc-function-infrastructure)$(nc-resource-keyvault)1001.vault.azure.net/"
          -ServiceBusConnection:fullyQualifiedNamespace "$(environment)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001.servicebus.windows.net"
        snd: >-
          -DynamicOptions:Authority "https://login.microsoftonline.com/"
          -DynamicOptions:ApiVersion "9.1"
          -AzureServiceBusOptions:SubmitQueueName "defra.trade.pts.application.submit"
          -AzureServiceBusOptions:UpdateQueueName "defra.trade.pts.application.update"
          -KeyVaultUri "https://$(Environment.Name)TRD$(nc-function-infrastructure)$(nc-resource-keyvault)1001.vault.azure.net/"
          -ServiceBusConnection:fullyQualifiedNamespace "$(environment)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001.servicebus.windows.net"
        pre: >-
          -DynamicOptions:Authority "https://login.microsoftonline.com/"
          -DynamicOptions:ApiVersion "9.1"
          -AzureServiceBusOptions:SubmitQueueName "defra.trade.pts.application.submit"
          -AzureServiceBusOptions:UpdateQueueName "defra.trade.pts.application.update"
          -KeyVaultUri "https://$(Environment.Name)TRD$(nc-function-infrastructure)$(nc-resource-keyvault)1001.vault.azure.net/"
          -ServiceBusConnection:fullyQualifiedNamespace "$(environment)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001.servicebus.windows.net"
        prd: >-
          -DynamicOptions:Authority "https://login.microsoftonline.com/"
          -DynamicOptions:ApiVersion "9.1"
          -AzureServiceBusOptions:SubmitQueueName "defra.trade.pts.application.submit"
          -AzureServiceBusOptions:UpdateQueueName "defra.trade.pts.application.update"
          -KeyVaultUri "https://$(Environment.Name)TRD$(nc-function-infrastructure)$(nc-resource-keyvault)1001.vault.azure.net/"
          -ServiceBusConnection:fullyQualifiedNamespace "$(environment)TRE$(nc-function-infrastructure)$(nc-resource-servicebus)1001.servicebus.windows.net"
    skipBuildTests: false
    runIntegrationTests: false
    runSonarScan: true